# Generated by Django 4.2 on 2023-04-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letsbeerit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='socialmembership',
            unique_together={('appuser', 'socialgroup')},
        ),
    ]
